//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentDateVisit
    {
        public long IDAppointmentDateVisit { get; set; }
        public long IDAppointment { get; set; }
        public System.DateTime DateTimeVisit { get; set; }
        public bool Approved { get; set; }
    
        public virtual Appointment Appointment { get; set; }

        public AppointmentDateVisit()
        {
        }

        public AppointmentDateVisit(long id, long ap, System.DateTime dateTime, bool approved)
        {
            this.IDAppointmentDateVisit = id;
            this.IDAppointment = ap;
            this.DateTimeVisit = dateTime;
            this.Approved = approved;
        }

        public AppointmentDateVisit(long ap, System.DateTime dateTime, bool approved = false)
        {
            this.IDAppointment = ap;
            this.DateTimeVisit = dateTime;
            this.Approved = approved;
        }
    }
}
