//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long IDArticle { get; set; }
        public string TitleArticle { get; set; }
        public string DescriptionArticle { get; set; }
        public string PsuedonymAuthor { get; set; }
        public long IDCategoryArticle { get; set; }
    
        public virtual CategoryArticle CategoryArticle { get; set; }

        public Article()
        {
        }

        public Article(long id, string tit, string desc, string auth, long cat)
        {
            this.IDArticle = id;
            this.TitleArticle = tit;
            this.DescriptionArticle = desc;
            this.PsuedonymAuthor = auth;
            this.IDCategoryArticle = cat;
        }

        public Article(string tit, string desc, string auth, long cat)
        {
            this.TitleArticle = tit;
            this.DescriptionArticle = desc;
            this.PsuedonymAuthor = auth;
            this.IDCategoryArticle = cat;
        }
    }
}
