//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMedFac
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryMedFac()
        {
            this.MedicalFacility = new HashSet<MedicalFacility>();
        }

        public CategoryMedFac(long id, string nam)
        {
            this.IDCategoryMedFac = id;
            this.NameCategory = nam;
        }

        public CategoryMedFac(string nam)
        {
            this.NameCategory = nam;
        }

        public long IDCategoryMedFac { get; set; }
        public string NameCategory { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalFacility> MedicalFacility { get; set; }
    }
}
