//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.Appointment = new HashSet<Appointment>();
            this.CompositionOfDoctors = new HashSet<CompositionOfDoctors>();
            this.DoctorSpeciality = new HashSet<DoctorSpeciality>();
        }

        public Doctor(long id, string fam, string nam, string pat, Nullable<System.DateTime> dat, bool gen)
        {
            this.IDDoctor = id;
            this.FamilyDoctor = fam;
            this.NameDoctor = nam;
            this.PatronymicDoctor = pat;
            this.DateBirthdayDoctor = dat;
            this.GenderDoctor = gen;
        }

        public Doctor(string fam, string nam, string pat, Nullable<System.DateTime> dat, bool gen)
        {
            this.FamilyDoctor = fam;
            this.NameDoctor = nam;
            this.PatronymicDoctor = pat;
            this.DateBirthdayDoctor = dat;
            this.GenderDoctor = gen;
        }

        public long IDDoctor { get; set; }
        public string FamilyDoctor { get; set; }
        public string NameDoctor { get; set; }
        public string PatronymicDoctor { get; set; }
        public Nullable<System.DateTime> DateBirthdayDoctor { get; set; }
        public bool GenderDoctor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionOfDoctors> CompositionOfDoctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorSpeciality> DoctorSpeciality { get; set; }
    }
}
