//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorSpeciality
    {
        public long IDDoctor { get; set; }
        public long IDSpeciality { get; set; }
        public bool CurrentSpeciality { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Speciality Speciality { get; set; }

        public DoctorSpeciality()
        {
        }
        public DoctorSpeciality(long doc, long spec, bool cur = true)
        {
            this.IDDoctor = doc;
            this.IDSpeciality = spec;
            this.CurrentSpeciality = cur;
        }
    }
}
