//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalFacility
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MedicalFacility()
        {
            this.Appointment = new HashSet<Appointment>();
            this.CompositionOfDoctors = new HashSet<CompositionOfDoctors>();
        }

        public MedicalFacility(long ID, string name, string street, string build, long cat, long city)
        {
            this.IDMedFac = ID;
            this.NameMedFac = name;
            this.Street = street;
            this.Building = build;
            this.IDCategoryMedFac = cat;
            this.IDCity = city;
        }

        public MedicalFacility(string name, string street, string build, long cat, long city)
        {
            this.NameMedFac = name;
            this.Street = street;
            this.Building = build;
            this.IDCategoryMedFac = cat;
            this.IDCity = city;
        }

        public long IDMedFac { get; set; }
        public string NameMedFac { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public long IDCategoryMedFac { get; set; }
        public long IDCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        public virtual CategoryMedFac CategoryMedFac { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompositionOfDoctors> CompositionOfDoctors { get; set; }
    }
}
