//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MedFacSystemEntities : DbContext
    {
        public MedFacSystemEntities()
            : base("name=MedFacSystemEntities")
        {
        }

        public MedFacSystemEntities(string connection)
            : base(connection)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<AppointmentDateVisit> AppointmentDateVisit { get; set; }
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<CategoryArticle> CategoryArticle { get; set; }
        public virtual DbSet<CategoryMedFac> CategoryMedFac { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<CompositionOfDoctors> CompositionOfDoctors { get; set; }
        public virtual DbSet<Doctor> Doctor { get; set; }
        public virtual DbSet<DoctorSpeciality> DoctorSpeciality { get; set; }
        public virtual DbSet<MedicalFacility> MedicalFacility { get; set; }
        public virtual DbSet<Speciality> Speciality { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
